name: Build HiFiOS x86

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf \
            /usr/share/dotnet \
            /opt/ghc \
            /opt/hostedtoolcache \
            /usr/local/lib/android

      - name: Enable community boards
        run: |
          mkdir -p userpatches
          echo 'EXPERT="yes"' >> userpatches/config-example.conf
          echo 'BUILD_ALL="yes"' >> userpatches/config-example.conf

      - name: Build HiFiOS
        run: |
          chmod +x compile.sh
          ./compile.sh \
            BOARD=x64 \
            BRANCH=current \
            RELEASE=trixie \
            BUILD_DESKTOP=no \
            BUILD_MINIMAL=yes \
            ENABLE_EXTENSIONS=hifios \
            KERNEL_CONFIGURE=no \
            CLEAN_LEVEL="none"
            2>&1 | tee build.log

      - uses: actions/upload-artifact@v4
        with:
          name: hifios-x86
          path: |
            output/images/*.img*
            output/images/*.sha
